[build-system]
requires = ["setuptools>=68", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/namdtools/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[project]
name = "namdtools"
dynamic = ["version"]
description = "Python tools for NAMD"
authors = [{ name="C. Lockhart", email="clockha2@gmu.edu" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fpathlib",
    "numpy",
    "pandas",
]

[project.optional-dependencies]
dev = ["pytest", "black", "sphinx", "sphinx-copybutton", "twine"]

[tool.setuptools.packages.find]
where = ["src"]
