{% set name = "namdtools" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/namdtools-{{ version }}.tar.gz
  sha256: 261538b981fc4421eb805149c226bf3e39e5aedb630436873199c616d1caf665

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=68
    - setuptools_scm
    - wheel
  run:
    - python >=3.12
    - fpathlib >=0.1.3
    - numpy
    - pandas
    - polars
    - sympy

test:
  imports:
    - namdtools

about:
  summary: Python tools for NAMD
  license: MIT
  home: https://github.com/LockhartLab/namdtools

extra:
  recipe-maintainers:
    - clockhart
